# -*- coding: utf-8 -*-
"""etl_Siniestros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3PU7PZx49sTmGjDex4Nrm9vphmo_csI

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

siniestros = pd.read_csv(url)

"""Exploración de datos"""

siniestros.head()

siniestros.info()

siniestros.isnull().sum()

siniestros.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

siniestros = normalizar_columnas(siniestros)
siniestros = limpiar_texto(siniestros)
siniestros = siniestros.drop_duplicates()

"""Funciones especificas"""

#Cambiar formato de estado
map_estado = {
"ABIERTO": "Abierto",
"Rechazado": "Cerrado",
"RECHAZADO" : "Cerrado"
}

siniestros ["estado"] = (
    siniestros["estado"]

    .replace(map_estado)
)
#Convertir fecha en datetime
siniestros["fecha_siniestro"] = pd.to_datetime(
    siniestros["fecha_siniestro"],
    errors="coerce",
    dayfirst=True,
    infer_datetime_format=True
)

#convertir monto en entero
siniestros["monto_siniestro"] = (
    siniestros["monto_siniestro"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

siniestros["monto_siniestro"] = pd.to_numeric(siniestros["monto_siniestro"], errors="coerce")

siniestros.info()

siniestros.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null

columnas_obligatorias = [
    "id_siniestro",
    "id_poliza",
    "fecha_siniestro",
    "monto_siniestro",
    "estado"
]

validos = siniestros [
 siniestros[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = siniestros [
 siniestros[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados_negativos= siniestros[
    (siniestros["monto_siniestro"] < 0)
].copy()

"""Motivo del rechazo"""

def motivo(row):
    motivos = []

    if pd.isna(row["id_siniestro"]):
        motivos.append("id_siniestro_nulo")

    if pd.isna(row["id_poliza"]):
        motivos.append("id_poliza_nulo")

    if pd.isna(row["fecha_siniestro"]):
        motivos.append("fecha_siniestro_nulo")

    if pd.isna(row["monto_siniestro"]) or row["monto_siniestro"] < 0:
        motivos.append("monto_siniestro_invalido")

    if pd.isna(row["estado"]):
        motivos.append("estado_nulo")

    return ", ".join(motivos)

"""Agregar motivo de rechazo

Exportar Archivos
"""

validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()

validos.to_sql(
    "siniestros",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From siniestros Limit 100",
    engine
)