# -*- coding: utf-8 -*-
"""etl_tipos_seguro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3PU7PZx49sTmGjDex4Nrm9vphmo_csI

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

tipos_seguro = pd.read_csv(url)

"""Exploración de datos"""

tipos_seguro.head()

tipos_seguro.info()

tipos_seguro.isnull().sum()

tipos_seguro.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

tipos_seguro = normalizar_columnas(tipos_seguro)
tipos_seguro = limpiar_texto(tipos_seguro)
tipos_seguro = tipos_seguro.drop_duplicates()

"""Funciones especificas"""

tipos_seguro.info()

tipos_seguro.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null

columnas_obligatorias = [
    "id_tipo_seguro",
    "tipo",
    "categoria",
    "riesgo_base"
]

validos = tipos_seguro [
 tipos_seguro[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = tipos_seguro [
 tipos_seguro[columnas_obligatorias].notna().all(axis=1)
].copy()

"""Motivo del rechazo"""

def motivo(row):
    motivos = []

    if pd.isna(row["id_tipo_seguro"]):
        motivos.append("id_tipo_seguro_nulo")

    if pd.isna(row["tipo"]):
        motivos.append("tipo_nulo")

    if pd.isna(row["categoria"]):
        motivos.append("categoria_es_nulo")

    if pd.isna(row["riesgo_base"]):
        motivos.append("riesgo_base_nulo")

    return ", ".join(motivos)

"""Agregar motivo de rechazo

Exportar Archivos
"""

validos.to_csv("tipos_seguro_curated.csv", index=False)
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()

validos.to_sql(
    "tipos_seguro",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From tipos_seguro Limit 100",
    engine
)