# -*- coding: utf-8 -*-
"""etl_Poliza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3PU7PZx49sTmGjDex4Nrm9vphmo_csI

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

polizas = pd.read_csv(url)

"""Exploración de datos"""

polizas.head()

polizas.info()

polizas.isnull().sum()

polizas.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

polizas = normalizar_columnas(polizas)
polizas = limpiar_texto(polizas)
polizas = polizas.drop_duplicates()

"""Funciones especificas"""

#Convertir fecha a dateTime
polizas["fecha_emision"] = pd.to_datetime(
    polizas["fecha_emision"].astype(str).str.strip(),
    errors="coerce"
)

#limpiar datos monetarios
polizas["prima"] = (
    polizas["prima"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

polizas["prima"] = pd.to_numeric(polizas["prima"], errors="coerce")

polizas.info()

polizas.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null
#2 fechas deben tener un formato valido
#3 los campos monetarios no pueden quedar como null

columnas_obligatorias = [
    "id_poliza",
    "fecha_emision",
    "id_cliente",
    "id_corredor",
    "id_aseguradora",
    "id_tipo_seguro",
    "prima",
    "comision",
    "monto_asegurado"
]

validos = polizas [
 polizas[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = polizas [
 polizas[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados_negativos= polizas[
    (polizas["prima"] < 0) |
    (polizas["comision"] < 0) |
    (polizas["monto_asegurado"] < 0)
].copy()

"""Motivo del rechazo"""

def motivo(row):
    motivos = []

    if pd.isna(row["id_poliza"]):
        motivos.append("id_poliza_nulo")

    if pd.isna(row["fecha_emision"]):
        motivos.append("fecha_emision_nulo")

    if pd.isna(row["id_cliente"]):
        motivos.append("id_cliente_nulo")

    if pd.isna(row["id_corredor"]):
        motivos.append("id_corredor_nulo")

    if pd.isna(row["id_aseguradora"]):
        motivos.append("id_aseguradora_nulo")

    if pd.isna(row["id_tipo_seguro"]):
        motivos.append("id_tipo_seguro_nulo")

    if pd.isna(row["prima"]) or row["prima"] < 0:
        motivos.append("prima_invalida")

    if pd.isna(row["comision"]) or row["comision"] < 0:
        motivos.append("comision_invalida")

    if pd.isna(row["monto_asegurado"]) or row["monto_asegurado"] < 0:
        motivos.append("monto_asegurado_invalido")

    return ", ".join(motivos)

"""Agregar motivo de rechazo

Exportar Archivos
"""

validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()

validos.to_sql(
    "polizas",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From polizas Limit 100",
    engine
)