# -*- coding: utf-8 -*-
"""etl_clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3PU7PZx49sTmGjDex4Nrm9vphmo_csI

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"

clientes = pd.read_csv(url)

"""Exploración de datos"""

clientes.head()

clientes.info()

clientes.isnull().sum()

clientes.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes = clientes.drop_duplicates()

"""Funciones especificas"""

import pandas as pd

# cambiar fecha a datetime
clientes["fecha_nacimiento"] = pd.to_datetime(
    clientes["fecha_nacimiento"].astype(str).str.strip(),
    errors="coerce"
)

# Asignación de género
map_genero = {
    "m": "Masculino",
    "M": "Masculino",
    "masculino": "Masculino",
    "male": "Masculino",

    "f": "Femenino",
    "F": "Femenino",
    "fem": "Femenino",
    "femenino": "Femenino",
    "female": "Femenino"
}

clientes["genero"] = clientes["genero"].map(map_genero)

nombres_masculinos = {
    "juan", "carlos", "jose", "luis", "miguel", "andres",
    "alex", "daniel", "fernando", "ricardo", "manuel"
}

nombres_femeninos = {
    "maria", "ana", "sofia", "laura", "carmen", "elena",
    "luisa", "valeria", "gabriela", "patricia"
}

def inferir_genero(row):
    if pd.isna(row["genero"]):
        nombre = str(row["nombre"]).split()[0].lower()

        if nombre in nombres_masculinos:
            return "Masculino"
        elif nombre in nombres_femeninos:
            return "Femenino"

    return row["genero"]

clientes["genero"] = clientes.apply(inferir_genero, axis=1)

#modificacion de ciudades

map_ciudades = {
    "SanMiguel" : "San Miguel",
    "Sta. Ana" : "Santa Ana",
    "S. Miguel" : "San Miguel",
    "LaLibertad" : "La Libertad",
    "SantaAna" : "Santa Ana",
    "Sonso" : "Sonsonate",
    "SS" : "San Salvador"
    }

clientes["ciudad"] = (
    clientes["ciudad"]

    .replace(map_ciudades)
)

#Configuracion del segmento

map_segmento = {
    "REGULAR" : "Regular",
    "Pyme" : "Pyme",
    "PYME" : "Pyme",
    "PREMIUM" : "Premium",
    "VIP" : "Vip"
}

clientes["segmento"] = (
    clientes["segmento"]

    .replace(map_segmento)
)

clientes.info()

clientes.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null
#2. El nombre no puede estar vacio

columnas_obligatorias = [
    "id_cliente",
    "nombre",
    "email",
    "genero",
    "fecha_nacimiento",
    "ciudad",
    "segmento"
]

validos = clientes [
 clientes[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = clientes [
 clientes[columnas_obligatorias].notna().all(axis=1)
].copy()

"""Motivo del rechazo"""

def motivo(row):
    motivos = []

    if pd.isna(row["id_cliente"]):
        motivos.append("id_tipo_cliente_nulo")

    if pd.isna(row["nombre"]):
        motivos.append("nombre_nulo")

    if pd.isna(row["email"]):
        motivos.append("email_es_nulo")

    if pd.isna(row["genero"]):
        motivos.append("genero_es_nulo")

    if pd.isna(row["fecha_nacimiento"]):
        motivos.append("fecha_nacimiento_es_nulo")

    if pd.isna(row["ciudad"]):
        motivos.append("ciudad_es_nula")

    if pd.isna(row["segmento"]):
        motivos.append("segmento_es_nulo")

    return ", ".join(motivos)

"""Agregar motivo de rechazo

Exportar Archivos
"""

validos.to_csv("clientes_curated.csv", index=False)
rechazados.to_csv("clientes_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()

validos.to_sql(
    "clientes",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From clientes Limit 100",
    engine
)